#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from P1.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "P1.y"

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
void yyerror(char*);
int yylex(void);

int flag = 0;

struct macro{
   char* id;
   char** args;
   int num;
   char* stmt;
   struct macro* next;
};

struct macro* head = NULL;
struct macro* curr = NULL;

char* reduce(char* fun, char* args){
   int checks = 0;
   struct macro* check = head;
   while(check != NULL){
      if(strcmp(check->id, fun) == 0){
         checks = 1;
         break;
      }
      check = check->next;
   }
   if(checks == 0){
      flag = 1;
   }
   char* values[1000];
   int ind = 0;
   char *t;
   //printf("%s\n", args);
   t = strtok(args, ",");
   while(t != NULL)
   {
      values[ind] = t;
      ind++;
      t = strtok(NULL, ",");
   }
   
   //printf("%d\n", ind);
   struct macro* temp = head;
   char* ans = malloc(1000*sizeof(char*));
   strcpy(ans, "");
   while(temp != NULL){
      if(strcmp(temp->id, fun) == 0){
         char *t;
         if(ind != temp->num){
            flag = 1;
            break;
         }
         char* copy = strdup(temp->stmt);
         t = strtok(temp->stmt, " \n");
         while(t != NULL)
         {
            //printf("%s\n", t);
            int check = 0;
            for(int i=0; i < temp->num; i++){
               //printf("%s\n", temp->args[i]);
               if(strcmp(temp->args[i], t) == 0){
                  //printf("%s\n", values[i]);
                  strcat(ans, " ");
                  strcat(ans, values[i]);
                  check = 1;
                  break;
               }
            }
            if(check == 0){
               strcat(ans, " ");
               strcat(ans, t);
            }
            t = strtok(NULL, " \n");
         }
         temp->stmt = strdup(copy);
      }
      temp = temp->next;
   }
   return ans;
}

#line 87 "P1.y"
typedef union{
   int num;
   char* str;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	NUMBER	258
#define	ID	259
#define	ADD	260
#define	SUB	261
#define	MUL	262
#define	DIV	263
#define	LEFT	264
#define	RIGHT	265
#define	PRINT	266
#define	EQ	267
#define	IF	268
#define	CUR_LEFT	269
#define	CUR_RIGHT	270
#define	SQ_LEFT	271
#define	SQ_RIGHT	272
#define	COMMA	273
#define	ELSE	274
#define	DO	275
#define	WHILE	276
#define	BOOL	277
#define	INT	278
#define	AND	279
#define	OR	280
#define	NEQ	281
#define	LEQ	282
#define	HASH	283
#define	CLASS	284
#define	EXTENDS	285
#define	PUBLIC	286
#define	STATIC	287
#define	VOID	288
#define	MAIN	289
#define	STR	290
#define	RETURN	291
#define	DOT	292
#define	LENGTH	293
#define	T	294
#define	F	295
#define	THIS	296
#define	NEW	297
#define	NOT	298
#define	DEFINE	299
#define	EOL	300
#define	THEN	301
#define	DONE	302


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int NUMBER;
static const int ID;
static const int ADD;
static const int SUB;
static const int MUL;
static const int DIV;
static const int LEFT;
static const int RIGHT;
static const int PRINT;
static const int EQ;
static const int IF;
static const int CUR_LEFT;
static const int CUR_RIGHT;
static const int SQ_LEFT;
static const int SQ_RIGHT;
static const int COMMA;
static const int ELSE;
static const int DO;
static const int WHILE;
static const int BOOL;
static const int INT;
static const int AND;
static const int OR;
static const int NEQ;
static const int LEQ;
static const int HASH;
static const int CLASS;
static const int EXTENDS;
static const int PUBLIC;
static const int STATIC;
static const int VOID;
static const int MAIN;
static const int STR;
static const int RETURN;
static const int DOT;
static const int LENGTH;
static const int T;
static const int F;
static const int THIS;
static const int NEW;
static const int NOT;
static const int DEFINE;
static const int EOL;
static const int THEN;
static const int DONE;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,NUMBER=258
	,ID=259
	,ADD=260
	,SUB=261
	,MUL=262
	,DIV=263
	,LEFT=264
	,RIGHT=265
	,PRINT=266
	,EQ=267
	,IF=268
	,CUR_LEFT=269
	,CUR_RIGHT=270
	,SQ_LEFT=271
	,SQ_RIGHT=272
	,COMMA=273
	,ELSE=274
	,DO=275
	,WHILE=276
	,BOOL=277
	,INT=278
	,AND=279
	,OR=280
	,NEQ=281
	,LEQ=282
	,HASH=283
	,CLASS=284
	,EXTENDS=285
	,PUBLIC=286
	,STATIC=287
	,VOID=288
	,MAIN=289
	,STR=290
	,RETURN=291
	,DOT=292
	,LENGTH=293
	,T=294
	,F=295
	,THIS=296
	,NEW=297
	,NOT=298
	,DEFINE=299
	,EOL=300
	,THEN=301
	,DONE=302


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::NUMBER=258;
const int YY_parse_CLASS::ID=259;
const int YY_parse_CLASS::ADD=260;
const int YY_parse_CLASS::SUB=261;
const int YY_parse_CLASS::MUL=262;
const int YY_parse_CLASS::DIV=263;
const int YY_parse_CLASS::LEFT=264;
const int YY_parse_CLASS::RIGHT=265;
const int YY_parse_CLASS::PRINT=266;
const int YY_parse_CLASS::EQ=267;
const int YY_parse_CLASS::IF=268;
const int YY_parse_CLASS::CUR_LEFT=269;
const int YY_parse_CLASS::CUR_RIGHT=270;
const int YY_parse_CLASS::SQ_LEFT=271;
const int YY_parse_CLASS::SQ_RIGHT=272;
const int YY_parse_CLASS::COMMA=273;
const int YY_parse_CLASS::ELSE=274;
const int YY_parse_CLASS::DO=275;
const int YY_parse_CLASS::WHILE=276;
const int YY_parse_CLASS::BOOL=277;
const int YY_parse_CLASS::INT=278;
const int YY_parse_CLASS::AND=279;
const int YY_parse_CLASS::OR=280;
const int YY_parse_CLASS::NEQ=281;
const int YY_parse_CLASS::LEQ=282;
const int YY_parse_CLASS::HASH=283;
const int YY_parse_CLASS::CLASS=284;
const int YY_parse_CLASS::EXTENDS=285;
const int YY_parse_CLASS::PUBLIC=286;
const int YY_parse_CLASS::STATIC=287;
const int YY_parse_CLASS::VOID=288;
const int YY_parse_CLASS::MAIN=289;
const int YY_parse_CLASS::STR=290;
const int YY_parse_CLASS::RETURN=291;
const int YY_parse_CLASS::DOT=292;
const int YY_parse_CLASS::LENGTH=293;
const int YY_parse_CLASS::T=294;
const int YY_parse_CLASS::F=295;
const int YY_parse_CLASS::THIS=296;
const int YY_parse_CLASS::NEW=297;
const int YY_parse_CLASS::NOT=298;
const int YY_parse_CLASS::DEFINE=299;
const int YY_parse_CLASS::EOL=300;
const int YY_parse_CLASS::THEN=301;
const int YY_parse_CLASS::DONE=302;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		246
#define	YYFLAG		-32768
#define	YYNTBASE	48

#define YYTRANSLATE(x) ((unsigned)(x) <= 302 ? yytranslate[x] : 65)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     4,     7,    10,    12,    16,    18,    20,    22,    26,
    31,    34,    39,    41,    43,    46,    49,    51,    53,    55,
    61,    66,    69,    73,    77,    81,    85,    89,    93,    97,
   101,   105,   110,   114,   116,   123,   129,   133,   138,   140,
   144,   147,   151,   157,   162,   170,   176,   184,   192,   198,
   203,   209,   211,   214,   216,   220,   231,   243,   255,   268,
   280,   293,   306,   320,   322,   325,   347,   353,   360,   366,
   371,   378,   386,   394,   403,   405,   408,   417,   427,   435,
   444,   453,   463,   465
};

static const short yyrhs[] = {    64,
    60,    62,     0,    64,    60,     0,    60,    62,     0,    60,
     0,    23,    16,    17,     0,    22,     0,    23,     0,     4,
     0,    49,     4,    45,     0,    50,    49,     4,    45,     0,
    49,     4,     0,    51,    18,    49,     4,     0,     4,     0,
     3,     0,     5,     3,     0,     6,     3,     0,    39,     0,
    40,     0,    41,     0,    42,    23,    16,    53,    17,     0,
    42,     4,     9,    10,     0,    43,    53,     0,     9,    53,
    10,     0,    52,    24,    52,     0,    52,    25,    52,     0,
    52,    26,    52,     0,    52,    27,    52,     0,    52,     5,
    52,     0,    52,     6,    52,     0,    52,     7,    52,     0,
    52,     8,    52,     0,    52,    16,    52,    17,     0,    52,
    37,    38,     0,    52,     0,    52,    37,     4,     9,    54,
    10,     0,    52,    37,     4,     9,    10,     0,     4,     9,
    10,     0,     4,     9,    54,    10,     0,    53,     0,    54,
    18,    53,     0,    14,    15,     0,    14,    56,    15,     0,
    11,     9,    53,    10,    45,     0,     4,    12,    53,    45,
     0,     4,    16,    53,    17,    12,    53,    45,     0,    13,
     9,    53,    10,    55,     0,    13,     9,    53,    10,    55,
    19,    55,     0,    20,    55,    21,     9,    53,    10,    45,
     0,    21,     9,    53,    10,    55,     0,     4,     9,    10,
    45,     0,     4,     9,    54,    10,    45,     0,    55,     0,
    56,    55,     0,     4,     0,    57,    18,     4,     0,    31,
    49,     4,     9,    10,    14,    36,    53,    45,    15,     0,
    31,    49,     4,     9,    10,    14,    56,    36,    53,    45,
    15,     0,    31,    49,     4,     9,    10,    14,    50,    36,
    53,    45,    15,     0,    31,    49,     4,     9,    10,    14,
    50,    56,    36,    53,    45,    15,     0,    31,    49,     4,
     9,    51,    10,    14,    36,    53,    45,    15,     0,    31,
    49,     4,     9,    51,    10,    14,    56,    36,    53,    45,
    15,     0,    31,    49,     4,     9,    51,    10,    14,    50,
    36,    53,    45,    15,     0,    31,    49,     4,     9,    51,
    10,    14,    50,    56,    36,    53,    45,    15,     0,    58,
     0,    59,    58,     0,    29,     4,    14,    31,    32,    33,
    34,     9,    35,    16,    17,     4,    10,    14,    11,     9,
    53,    10,    45,    15,    15,     0,    29,     4,    14,    59,
    15,     0,    29,     4,    14,    50,    59,    15,     0,    29,
     4,    14,    50,    15,     0,    29,     4,    14,    15,     0,
    29,     4,    30,     4,    14,    15,     0,    29,     4,    30,
     4,    14,    59,    15,     0,    29,     4,    30,     4,    14,
    50,    15,     0,    29,     4,    30,     4,    14,    50,    59,
    15,     0,    61,     0,    62,    61,     0,    28,    44,     4,
     9,    10,     9,    53,    10,     0,    28,    44,     4,     9,
    57,    10,     9,    53,    10,     0,    28,    44,     4,     9,
    10,    14,    15,     0,    28,    44,     4,     9,    10,    14,
    56,    15,     0,    28,    44,     4,     9,    57,    10,    14,
    15,     0,    28,    44,     4,     9,    57,    10,    14,    56,
    15,     0,    63,     0,    64,    63,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   114,   115,   116,   117,   124,   131,   132,   133,   137,   144,
   152,   159,   168,   169,   170,   176,   182,   183,   184,   185,
   191,   198,   204,   214,   221,   229,   236,   243,   250,   257,
   264,   271,   278,   284,   287,   293,   299,   339,   349,   352,
   361,   368,   375,   381,   387,   393,   399,   405,   411,   417,
   455,   460,   461,   470,   473,   482,   496,   511,   526,   542,
   557,   573,   589,   608,   611,   618,   646,   652,   658,   664,
   670,   676,   682,   688,   696,   697,   705,   734,   781,   810,
   839,   877,   918,   919
};

static const char * const yytname[] = {   "$","error","$illegal.","NUMBER","ID",
"ADD","SUB","MUL","DIV","LEFT","RIGHT","PRINT","EQ","IF","CUR_LEFT","CUR_RIGHT",
"SQ_LEFT","SQ_RIGHT","COMMA","ELSE","DO","WHILE","BOOL","INT","AND","OR","NEQ",
"LEQ","HASH","CLASS","EXTENDS","PUBLIC","STATIC","VOID","MAIN","STR","RETURN",
"DOT","LENGTH","T","F","THIS","NEW","NOT","DEFINE","EOL","THEN","DONE","goal",
"var","var1","var2","priexp","exp","exp1","statement","statement1","id1","method",
"method1","mainclass","typedecl","typedecl1","macrodef","macrodef1",""
};
#endif

static const short yyr1[] = {     0,
    48,    48,    48,    48,    49,    49,    49,    49,    50,    50,
    51,    51,    52,    52,    52,    52,    52,    52,    52,    52,
    52,    52,    52,    53,    53,    53,    53,    53,    53,    53,
    53,    53,    53,    53,    53,    53,    53,    53,    54,    54,
    55,    55,    55,    55,    55,    55,    55,    55,    55,    55,
    55,    56,    56,    57,    57,    58,    58,    58,    58,    58,
    58,    58,    58,    59,    59,    60,    61,    61,    61,    61,
    61,    61,    61,    61,    62,    62,    63,    63,    63,    63,
    63,    63,    64,    64
};

static const short yyr2[] = {     0,
     3,     2,     2,     1,     3,     1,     1,     1,     3,     4,
     2,     4,     1,     1,     2,     2,     1,     1,     1,     5,
     4,     2,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     4,     3,     1,     6,     5,     3,     4,     1,     3,
     2,     3,     5,     4,     7,     5,     7,     7,     5,     4,
     5,     1,     2,     1,     3,    10,    11,    11,    12,    11,
    12,    12,    13,     1,     2,    21,     5,     6,     5,     4,
     6,     7,     7,     8,     1,     2,     8,     9,     7,     8,
     8,     9,     1,     2
};

static const short yydefact[] = {     0,
     0,     0,     4,    83,     0,     0,     0,     0,    75,     3,
     2,    84,     0,     0,     0,    76,     1,     0,     0,     0,
     0,    54,     0,     0,     0,     8,    70,     6,     7,     0,
     0,     0,    64,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,    69,     0,     0,    67,    65,     0,    14,
    13,     0,     0,     0,    17,    18,    19,     0,     0,    34,
     0,     0,     0,     0,     0,    79,     0,     0,    52,     0,
     0,     0,    55,     0,     5,     0,     9,     0,    68,    71,
     0,     0,     0,    15,    16,     0,     0,     0,    22,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,    77,
     0,     0,     0,     0,     0,    41,     0,     0,     0,    80,
    53,     0,    81,     0,     0,     0,    10,    73,     0,    72,
    37,    39,     0,    23,     0,     0,    13,    28,    29,    30,
    31,     0,    24,    25,    26,    27,     0,    33,     0,     0,
     0,     0,     0,     0,    42,     0,     0,    78,    82,     0,
     0,     0,     0,    74,    38,     0,    21,     0,    32,     0,
    50,     0,    44,     0,     0,     0,     0,     0,     0,     0,
    11,     0,     0,    40,    20,    36,     0,    51,     0,    43,
    46,     0,    49,     0,     8,     0,     0,     0,     0,     0,
    35,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,    12,    45,    47,    48,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,    56,     0,     0,     0,
     0,     0,     0,     0,     0,    58,     0,    57,    60,     0,
     0,     0,     0,    59,    62,     0,    61,     0,    63,     0,
     0,     0,    66,     0,     0,     0
};

static const short yydefgoto[] = {   244,
    31,    32,   153,    60,   122,   123,    69,    70,    24,    33,
    34,     3,     9,    10,     4,     5
};

static const short yypact[] = {    -4,
   -37,    32,   -13,-32768,    -4,    51,    57,    82,-32768,   -13,
   -13,-32768,    91,    77,     1,-32768,   -13,    47,   108,     6,
   120,-32768,     8,    73,   109,-32768,-32768,-32768,   129,    10,
   143,    90,-32768,    12,   138,    56,   301,    71,   153,   131,
   149,   163,   126,-32768,   164,    19,-32768,-32768,   107,-32768,
   166,   170,   173,    56,-32768,-32768,-32768,     7,    56,   205,
   174,   123,   176,   186,   313,-32768,   373,   187,-32768,   325,
    56,   337,-32768,   193,-32768,   194,-32768,   169,-32768,-32768,
   147,    33,    35,-32768,-32768,   198,   200,   199,-32768,   177,
   177,   177,   177,   177,   177,   177,   177,   177,     9,-32768,
   150,    56,    56,    56,    56,-32768,   349,   201,    56,-32768,
-32768,   213,-32768,   361,   189,   184,-32768,-32768,    39,-32768,
-32768,-32768,    74,-32768,   215,    56,-32768,-32768,-32768,-32768,
-32768,   209,-32768,-32768,-32768,-32768,   218,-32768,   183,    92,
   188,   223,   231,   234,-32768,   236,   237,-32768,-32768,   238,
   250,   247,    96,-32768,-32768,    56,-32768,   248,-32768,   195,
-32768,   221,-32768,   256,   224,   373,    56,   373,   261,   235,
-32768,   274,    10,-32768,-32768,-32768,    97,-32768,    56,-32768,
   270,   280,-32768,   288,   123,    56,   239,    68,   259,   289,
-32768,   257,   373,   264,   296,   265,    56,   105,    56,    56,
   263,   283,-32768,-32768,-32768,-32768,   297,   298,   273,    56,
   275,   285,    56,   287,    56,   314,-32768,   316,   290,   317,
   322,   299,    56,   302,   333,-32768,   328,-32768,-32768,   334,
   309,   340,    56,-32768,-32768,   341,-32768,   351,-32768,   321,
   344,   352,-32768,   368,   371,-32768
};

static const short yypgoto[] = {-32768,
   -29,   -43,-32768,   305,   -36,   -97,   -65,   -53,-32768,   -26,
   -23,   374,    36,   362,   375,-32768
};


#define	YYLAST		403


static const short yytable[] = {    61,
    42,   108,    45,   140,   111,    81,     6,    48,    46,    26,
    87,   107,   137,    26,    20,     8,    36,    86,   114,    48,
    27,    37,    89,     1,     2,    82,    47,    28,    29,    88,
    21,    28,    29,    79,   112,     7,    30,    50,    51,    52,
    53,   111,    30,    54,   121,    16,   138,   120,   111,    30,
    22,    45,    16,   154,    13,    48,    23,   119,    50,    51,
    52,    53,   177,    30,    54,   141,   142,   143,   144,    30,
    14,    62,   147,    55,    56,    57,    58,    59,    63,    71,
    64,    65,    38,   155,    72,    15,   152,    67,    68,   158,
    39,   156,    48,    26,    55,    56,    57,    58,    59,    18,
   181,   162,   183,   199,    44,   172,   191,    19,    62,   156,
    26,    28,    29,   173,   156,    63,   188,    64,    65,   174,
    30,    80,   111,    35,    67,    68,   187,   205,    28,    29,
   182,   101,   111,   198,   102,   202,   111,    30,   103,    25,
   210,    40,   192,   190,    41,   201,    43,   214,   111,   196,
    26,    49,    50,    51,    52,    53,    73,    45,    54,   139,
   209,   118,   211,   212,    74,    75,    76,    78,    28,    29,
    77,    45,    84,   219,    83,    85,   222,    30,   224,    50,
   127,    52,    53,   100,   104,    54,   231,    26,    55,    56,
    57,    58,    59,   151,   105,   109,   238,    50,    51,    52,
    53,   115,   116,    54,   176,    28,    29,   124,   125,    90,
    91,    92,    93,   117,   126,    55,    56,    57,    58,    59,
    94,   146,   148,   150,   157,   159,   160,   161,    95,    96,
    97,    98,   163,    55,    56,    57,    58,    59,   185,   164,
   165,    99,   185,   166,   167,    63,   168,    64,    65,    63,
   171,    64,    65,   169,    67,    68,    28,    29,    67,    68,
    28,    29,   185,   170,   175,   178,   185,   179,   180,    63,
   186,    64,    65,    63,   197,    64,    65,   184,    67,    68,
    28,    29,    67,    68,    28,    29,    62,   189,   193,   194,
    62,   195,   203,    63,   200,    64,    65,    63,   213,    64,
    65,   204,    67,    68,    62,   207,    67,    68,   206,   208,
   216,    63,   217,    64,    65,    66,    62,   218,   215,   220,
    67,    68,   223,    63,   225,    64,    65,   106,    62,   221,
   226,   228,    67,    68,   227,    63,   229,    64,    65,   110,
    62,   233,   234,   230,    67,    68,   232,    63,   235,    64,
    65,   113,    62,   236,   237,   239,    67,    68,   242,    63,
   240,    64,    65,   145,    62,   241,   243,   245,    67,    68,
   246,    63,    17,    64,    65,   149,    62,     0,    11,    12,
    67,    68,     0,    63,     0,    64,    65,     0,     0,     0,
     0,     0,    67,    68,   128,   129,   130,   131,   132,   133,
   134,   135,   136
};

static const short yycheck[] = {    36,
    30,    67,    32,   101,    70,    49,    44,    34,    32,     4,
     4,    65,     4,     4,    14,    29,     9,    54,    72,    46,
    15,    14,    59,    28,    29,    49,    15,    22,    23,    23,
    30,    22,    23,    15,    71,     4,    31,     3,     4,     5,
     6,   107,    31,     9,    10,    10,    38,    15,   114,    31,
     4,    81,    17,    15,     4,    82,    10,    81,     3,     4,
     5,     6,   160,    31,     9,   102,   103,   104,   105,    31,
    14,     4,   109,    39,    40,    41,    42,    43,    11,     9,
    13,    14,    10,    10,    14,     4,   116,    20,    21,   126,
    18,    18,   119,     4,    39,    40,    41,    42,    43,     9,
   166,    10,   168,    36,    15,    10,    10,    31,     4,    18,
     4,    22,    23,    18,    18,    11,   170,    13,    14,   156,
    31,    15,   188,     4,    20,    21,   170,   193,    22,    23,
   167,     9,   198,   187,    12,   189,   202,    31,    16,    32,
    36,    33,   179,   173,    16,   189,     4,   201,   214,   186,
     4,    14,     3,     4,     5,     6,     4,   187,     9,    10,
   197,    15,   199,   200,    34,    17,     4,     4,    22,    23,
    45,   201,     3,   210,     9,     3,   213,    31,   215,     3,
     4,     5,     6,    10,     9,     9,   223,     4,    39,    40,
    41,    42,    43,    10,     9,     9,   233,     3,     4,     5,
     6,     9,     9,     9,    10,    22,    23,    10,     9,     5,
     6,     7,     8,    45,    16,    39,    40,    41,    42,    43,
    16,    21,    10,    35,    10,    17,     9,    45,    24,    25,
    26,    27,    45,    39,    40,    41,    42,    43,     4,    17,
    10,    37,     4,    10,     9,    11,    10,    13,    14,    11,
     4,    13,    14,    16,    20,    21,    22,    23,    20,    21,
    22,    23,     4,    14,    17,    45,     4,    12,    45,    11,
    36,    13,    14,    11,    36,    13,    14,    17,    20,    21,
    22,    23,    20,    21,    22,    23,     4,    14,    19,    10,
     4,     4,     4,    11,    36,    13,    14,    11,    36,    13,
    14,    45,    20,    21,     4,    10,    20,    21,    45,    45,
    14,    11,    15,    13,    14,    15,     4,    45,    36,    45,
    20,    21,    36,    11,    11,    13,    14,    15,     4,    45,
    15,    15,    20,    21,    45,    11,    15,    13,    14,    15,
     4,     9,    15,    45,    20,    21,    45,    11,    15,    13,
    14,    15,     4,    45,    15,    15,    20,    21,    15,    11,
    10,    13,    14,    15,     4,    45,    15,     0,    20,    21,
     0,    11,    11,    13,    14,    15,     4,    -1,     5,     5,
    20,    21,    -1,    11,    -1,    13,    14,    -1,    -1,    -1,
    -1,    -1,    20,    21,    90,    91,    92,    93,    94,    95,
    96,    97,    98
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 114 "P1.y"
{if(!flag){printf("%s\n%s\n", yyvsp[-1].str, yyvsp[0].str);}else{printf("// Failed to parse macrojava code.");};
    break;}
case 2:
#line 115 "P1.y"
{if(!flag){printf("%s\n", yyvsp[0].str);}else{printf("// Failed to parse macrojava code.");};
    break;}
case 3:
#line 116 "P1.y"
{if(!flag){printf("%s\n%s\n", yyvsp[-1].str, yyvsp[0].str);}else{printf("// Failed to parse macrojava code.");};
    break;}
case 4:
#line 117 "P1.y"
{
   if(!flag){printf("%s\n", yyvsp[0].str);}
   else{printf("// Failed to parse macrojava code.");}
;
    break;}
case 5:
#line 124 "P1.y"
{
   char* s = malloc(sizeof(char)*(7+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+4));
   strcpy(s, yyvsp[-2].str);
   strcat(s, " ");
   strcat(s,yyvsp[-1].str); strcat(s, " ");strcat(s,yyvsp[0].str); strcat(s, " ");
   yyval.str=s;
;
    break;}
case 6:
#line 131 "P1.y"
{yyval.str = yyvsp[0].str;;
    break;}
case 7:
#line 132 "P1.y"
{yyval.str = yyvsp[0].str;;
    break;}
case 8:
#line 133 "P1.y"
{yyval.str = yyvsp[0].str;;
    break;}
case 9:
#line 137 "P1.y"
{
   char* s = malloc(sizeof(char)*(7+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+4));
   strcpy(s, yyvsp[-2].str);
   strcat(s, " ");
   strcat(s,yyvsp[-1].str); strcat(s, " ");strcat(s,yyvsp[0].str); strcat(s, " ");
   yyval.str=s;
;
    break;}
case 10:
#line 144 "P1.y"
{
   char* s = malloc(sizeof(char)*(7+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+5));
   strcpy(s, yyvsp[-3].str);strcat(s, " ");
   strcat(s,yyvsp[-2].str);strcat(s, " ");strcat(s,yyvsp[-1].str); strcat(s, " ");strcat(s,yyvsp[0].str); strcat(s, " ");
   yyval.str=s;
;
    break;}
case 11:
#line 152 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+4));
   strcpy(s, yyvsp[-1].str);
   strcat(s, " ");
   strcat(s,yyvsp[0].str); strcat(s, " ");
   yyval.str=s;
;
    break;}
case 12:
#line 159 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+4));
   strcpy(s, yyvsp[-3].str);strcat(s, " ");
   strcat(s,yyvsp[-2].str);strcat(s, " ");strcat(s,yyvsp[-1].str); strcat(s, " ");strcat(s,yyvsp[0].str); strcat(s, " ");
   yyval.str=s;
;
    break;}
case 13:
#line 168 "P1.y"
{yyval.str = yyvsp[0].str;;
    break;}
case 14:
#line 169 "P1.y"
{yyval.str = yyvsp[0].str;;
    break;}
case 15:
#line 170 "P1.y"
{
   char* s = malloc(sizeof(char)*(strlen(yyvsp[0].str)+5));
   strcpy(s, " + ");
   strcat(s, yyvsp[0].str);
   yyval.str=s;
;
    break;}
case 16:
#line 176 "P1.y"
{
   char* s = malloc(sizeof(char)*(strlen(yyvsp[0].str)+5));
   strcpy(s, " - ");
   strcat(s, yyvsp[0].str);
   yyval.str=s;
;
    break;}
case 17:
#line 182 "P1.y"
{yyval.str = " true ";;
    break;}
case 18:
#line 183 "P1.y"
{yyval.str = " false ";;
    break;}
case 19:
#line 184 "P1.y"
{yyval.str = " this ";;
    break;}
case 20:
#line 185 "P1.y"
{
      char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-4].str)+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+6));
      strcpy(s, yyvsp[-4].str); strcat(s, " ");
      strcat(s,yyvsp[-3].str);strcat(s, " ");strcat(s,yyvsp[-2].str); strcat(s, " ");strcat(s, yyvsp[-1].str);strcat(s, " ");strcat(s, yyvsp[0].str); strcat(s, " ");
      yyval.str=s;
;
    break;}
case 21:
#line 191 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+4));
   strcpy(s, yyvsp[-3].str);
   strcat(s, " ");
   strcat(s,yyvsp[-2].str);strcat(s, " ");strcat(s,yyvsp[-1].str);strcat(s, " ");strcat(s, yyvsp[0].str); strcat(s, " ");
   yyval.str=s;
;
    break;}
case 22:
#line 198 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+3));
   strcpy(s, yyvsp[-1].str); strcat(s, " ");
   strcat(s, yyvsp[0].str); strcat(s, " ");
   yyval.str=s;
;
    break;}
case 23:
#line 204 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+3));
   strcpy(s, yyvsp[-2].str);
   strcat(s, " ");
   strcat(s,yyvsp[-1].str); strcat(s, " ");strcat(s,yyvsp[0].str); strcat(s, " ");
   yyval.str=s;
;
    break;}
case 24:
#line 214 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-2].str)+2+strlen(yyvsp[0].str)+3));
   strcpy(s, yyvsp[-2].str);
   strcat(s, " ");
   strcat(s,"&& ");strcat(s,yyvsp[0].str);
   yyval.str=s;
;
    break;}
case 25:
#line 222 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-2].str)+2+strlen(yyvsp[0].str)+3));
   strcpy(s, yyvsp[-2].str);
   strcat(s, " ");
   strcat(s,"|| ");strcat(s,yyvsp[0].str);
   yyval.str=s;
;
    break;}
case 26:
#line 229 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-2].str)+2+strlen(yyvsp[0].str)+3));
   strcpy(s, yyvsp[-2].str);
   strcat(s, " ");
   strcat(s,"!= ");strcat(s,yyvsp[0].str);
   yyval.str=s;
;
    break;}
case 27:
#line 236 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-2].str)+2+strlen(yyvsp[0].str)+3));
   strcpy(s, yyvsp[-2].str);
   strcat(s, " ");
   strcat(s,"<= ");strcat(s,yyvsp[0].str);
   yyval.str=s;
;
    break;}
case 28:
#line 243 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-2].str)+2+strlen(yyvsp[0].str)+3));
   strcpy(s, yyvsp[-2].str);
   strcat(s, " ");
   strcat(s,"+ ");strcat(s,yyvsp[0].str);
   yyval.str=s;
;
    break;}
case 29:
#line 250 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-2].str)+2+strlen(yyvsp[0].str)+3));
   strcpy(s, yyvsp[-2].str);
   strcat(s, " ");
   strcat(s,"- ");strcat(s,yyvsp[0].str);
   yyval.str=s;
;
    break;}
case 30:
#line 257 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-2].str)+2+strlen(yyvsp[0].str)+3));
   strcpy(s, yyvsp[-2].str);
   strcat(s, " ");
   strcat(s,"* ");strcat(s,yyvsp[0].str);
   yyval.str=s;
;
    break;}
case 31:
#line 264 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-2].str)+2+strlen(yyvsp[0].str)+3));
   strcpy(s, yyvsp[-2].str);
   strcat(s, " ");
   strcat(s,"/ ");strcat(s,yyvsp[0].str);
   yyval.str=s;
;
    break;}
case 32:
#line 271 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+4));
   strcpy(s, yyvsp[-3].str);
   strcat(s, " ");
   strcat(s,yyvsp[-2].str); strcat(s, " ");strcat(s,yyvsp[-1].str); strcat(s, " ");strcat(s, yyvsp[0].str); strcat(s, " ");
   yyval.str=s;
;
    break;}
case 33:
#line 278 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-2].str)+2+6+3));
   strcpy(s, yyvsp[-2].str);
   strcat(s," .");strcat(s,"length ");
   yyval.str=s;
;
    break;}
case 34:
#line 284 "P1.y"
{ 
   yyval.str=yyvsp[0].str;
;
    break;}
case 35:
#line 287 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-5].str)+strlen(yyvsp[-4].str)+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+6));
   strcpy(s, yyvsp[-5].str); strcat(s, " ");
   strcat(s,yyvsp[-4].str);strcat(s, " ");strcat(s,yyvsp[-3].str); strcat(s, " ");strcat(s, yyvsp[-2].str);strcat(s, " ");strcat(s, yyvsp[-1].str); strcat(s, " ");strcat(s, yyvsp[0].str); strcat(s, " ");
   yyval.str=s;
;
    break;}
case 36:
#line 293 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-4].str)+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+6));
   strcpy(s, yyvsp[-4].str); strcat(s, " ");
   strcat(s,yyvsp[-3].str);strcat(s, " ");strcat(s,yyvsp[-2].str); strcat(s, " ");strcat(s, yyvsp[-1].str);strcat(s, " ");strcat(s, yyvsp[0].str); strcat(s, " ");
   yyval.str=s;
;
    break;}
case 37:
#line 299 "P1.y"
{
      int checks = 0;
      struct macro* check = head;
      while(check != NULL){
         if(strcmp(check->id, yyvsp[-2].str) == 0){
            checks = 1;
            break;
         }
         check = check->next;
      }
      if(checks == 0){
         flag = 1;
      }
      struct macro* temp = head;
      char* ans = malloc(1000*sizeof(char*));
      strcpy(ans, "( ");
      while(temp != NULL){
         if(strcmp(temp->id, yyvsp[-2].str) == 0){
            if(temp->num != 0){
               //printf("%d\n", temp->num);
               flag = 1;
               break;
            }
            char *t;
            char* copy = strdup(temp->stmt);
            t = strtok(temp->stmt, " ");
            while(t != NULL)
            {
               strcat(ans, t);
               strcat(ans, " ");
               t = strtok(NULL, " ");
            }
            temp->stmt = copy;
            break;
         }
         temp = temp->next;
      }
      strcat(ans, " )");
      yyval.str = ans;
;
    break;}
case 38:
#line 339 "P1.y"
{
      char* ans = reduce(yyvsp[-3].str, yyvsp[-1].str);
      char* ans1 = malloc(sizeof(char)*(5+strlen(ans)));
      strcat(ans1, "( ");
      strcat(ans1, ans);
      strcat(ans1, " )");
      yyval.str = ans1;
;
    break;}
case 39:
#line 349 "P1.y"
{
   yyval.str = yyvsp[0].str;
;
    break;}
case 40:
#line 352 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-2].str)+2+strlen(yyvsp[0].str)+3));
   strcpy(s, yyvsp[-2].str);
   strcat(s, ", ");
   strcat(s,yyvsp[0].str);
   yyval.str=s;
;
    break;}
case 41:
#line 361 "P1.y"
{
      char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+3));
      strcpy(s, yyvsp[-1].str);
      strcat(s, " ");
      strcat(s,yyvsp[0].str);strcat(s, " ");
      yyval.str=s;
;
    break;}
case 42:
#line 368 "P1.y"
{
      char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+3));
      strcpy(s, yyvsp[-2].str);
      strcat(s, " ");
      strcat(s,yyvsp[-1].str);strcat(s, " ");strcat(s,yyvsp[0].str);strcat(s, " ");
      yyval.str=s;
;
    break;}
case 43:
#line 375 "P1.y"
{
      char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-4].str)+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+6));
      strcpy(s, yyvsp[-4].str);strcat(s, " ");
      strcat(s,yyvsp[-3].str);strcat(s, " ");strcat(s,yyvsp[-2].str);strcat(s, " ");strcat(s, yyvsp[-1].str);strcat(s, " ");strcat(s, yyvsp[0].str);strcat(s, " ");
      yyval.str=s;
;
    break;}
case 44:
#line 381 "P1.y"
{
      char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+6));
      strcpy(s, yyvsp[-3].str);strcat(s, " ");
      strcat(s,yyvsp[-2].str);strcat(s, " ");strcat(s,yyvsp[-1].str);strcat(s, " ");strcat(s, yyvsp[0].str);strcat(s, " ");
      yyval.str=s;
;
    break;}
case 45:
#line 387 "P1.y"
{
      char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-6].str)+strlen(yyvsp[-5].str)+strlen(yyvsp[-4].str)+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+7));
      strcpy(s, yyvsp[-6].str);strcat(s, " ");
      strcat(s,yyvsp[-5].str);strcat(s, " ");strcat(s,yyvsp[-4].str);strcat(s, " ");strcat(s, yyvsp[-3].str);strcat(s, " ");strcat(s, yyvsp[-2].str);strcat(s, " ");strcat(s, yyvsp[-1].str);strcat(s, " ");strcat(s, yyvsp[0].str);strcat(s, " ");
      yyval.str=s;
;
    break;}
case 46:
#line 393 "P1.y"
{
      char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-4].str)+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+6));
      strcpy(s, yyvsp[-4].str);strcat(s, " ");
      strcat(s,yyvsp[-3].str);strcat(s, " ");strcat(s,yyvsp[-2].str);strcat(s, " ");strcat(s, yyvsp[-1].str);strcat(s, " ");strcat(s, yyvsp[0].str);strcat(s, " ");
      yyval.str=s;
;
    break;}
case 47:
#line 399 "P1.y"
{
      char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-6].str)+strlen(yyvsp[-5].str)+strlen(yyvsp[-4].str)+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+7));
      strcpy(s, yyvsp[-6].str);strcat(s, " ");
      strcat(s,yyvsp[-5].str);strcat(s, " ");strcat(s,yyvsp[-4].str);strcat(s, " ");strcat(s, yyvsp[-3].str);strcat(s, " ");strcat(s, yyvsp[-2].str);strcat(s, "\n");strcat(s, yyvsp[-1].str);strcat(s, " ");strcat(s, yyvsp[0].str);strcat(s, " ");
      yyval.str=s;
;
    break;}
case 48:
#line 405 "P1.y"
{
      char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-6].str)+strlen(yyvsp[-5].str)+strlen(yyvsp[-4].str)+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+7));
      strcpy(s, yyvsp[-6].str);strcat(s, " ");
      strcat(s,yyvsp[-5].str);strcat(s, " ");strcat(s,yyvsp[-4].str);strcat(s, " ");strcat(s, yyvsp[-3].str);strcat(s, " ");strcat(s, yyvsp[-2].str);strcat(s, " ");strcat(s, yyvsp[-1].str);strcat(s, " ");strcat(s, yyvsp[0].str);strcat(s, " ");
      yyval.str=s;
;
    break;}
case 49:
#line 411 "P1.y"
{
      char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-4].str)+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+6));
      strcpy(s, yyvsp[-4].str);strcat(s, " ");
      strcat(s,yyvsp[-3].str);strcat(s, " ");strcat(s,yyvsp[-2].str);strcat(s, " ");strcat(s, yyvsp[-1].str);strcat(s, " ");strcat(s, yyvsp[0].str);strcat(s, " ");
      yyval.str=s;
;
    break;}
case 50:
#line 417 "P1.y"
{
      int checks = 0;
      struct macro* check = head;
      while(check != NULL){
         if(strcmp(check->id, yyvsp[-3].str) == 0){
            checks = 1;
            break;
         }
         check = check->next;
      }
      if(checks == 0){
         flag = 1;
      }
      struct macro* temp = head;
      char* ans = malloc(1000*sizeof(char*));
      strcpy(ans, "");
      while(temp != NULL){
         if(strcmp(temp->id, yyvsp[-3].str) == 0){
            if(temp->num != 0){
               flag = 1;
               break;
            }
            char *t;
            char* copy = strdup(temp->stmt);
            t = strtok(temp->stmt, " ");
            while(t != NULL)
            {
               strcat(ans, t);
               strcat(ans, " ");
               t = strtok(NULL, " ");
            }
            temp->stmt = copy;
            break;
         }
         temp = temp->next;
      }
      yyval.str = ans;
;
    break;}
case 51:
#line 455 "P1.y"
{
      yyval.str = reduce(yyvsp[-4].str, yyvsp[-2].str);
;
    break;}
case 52:
#line 460 "P1.y"
{yyval.str = yyvsp[0].str;;
    break;}
case 53:
#line 461 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+3));
   strcpy(s, yyvsp[-1].str);
   strcat(s, "\n");
   strcat(s,yyvsp[0].str);strcat(s, " ");
   yyval.str=s;
;
    break;}
case 54:
#line 470 "P1.y"
{
   yyval.str = yyvsp[0].str;
;
    break;}
case 55:
#line 473 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-2].str)+2+strlen(yyvsp[0].str)+3));
   strcpy(s, yyvsp[-2].str);
   strcat(s, ", ");
   strcat(s,yyvsp[0].str);strcat(s, " ");
   yyval.str=s;
;
    break;}
case 56:
#line 482 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-9].str)+strlen(yyvsp[-8].str)+strlen(yyvsp[-7].str)+strlen(yyvsp[-6].str)+strlen(yyvsp[-5].str)+strlen(yyvsp[-4].str)+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+16));
   strcpy(s, yyvsp[-9].str);strcat(s, " ");
   strcat(s,yyvsp[-8].str);strcat(s, " ");
   strcat(s,yyvsp[-7].str);strcat(s, " ");
   strcat(s,yyvsp[-6].str);strcat(s, " ");
   strcat(s,yyvsp[-5].str);strcat(s, " ");
   strcat(s,yyvsp[-4].str);strcat(s, "\n");
   strcat(s,yyvsp[-3].str);strcat(s, " ");
   strcat(s,yyvsp[-2].str);strcat(s, " ");
   strcat(s,yyvsp[-1].str);strcat(s, " ");
   strcat(s,yyvsp[0].str);strcat(s, "\n");
   yyval.str=s;
;
    break;}
case 57:
#line 496 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-10].str)+strlen(yyvsp[-9].str)+strlen(yyvsp[-8].str)+strlen(yyvsp[-7].str)+strlen(yyvsp[-6].str)+strlen(yyvsp[-5].str)+strlen(yyvsp[-4].str)+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+16));
   strcpy(s, yyvsp[-10].str);strcat(s, " ");
   strcat(s,yyvsp[-9].str);strcat(s, " ");
   strcat(s,yyvsp[-8].str);strcat(s, " ");
   strcat(s,yyvsp[-7].str);strcat(s, " ");
   strcat(s,yyvsp[-6].str);strcat(s, " ");
   strcat(s,yyvsp[-5].str);strcat(s, "\n");
   strcat(s,yyvsp[-4].str);strcat(s, " ");
   strcat(s,yyvsp[-3].str);strcat(s, " ");
   strcat(s,yyvsp[-2].str);strcat(s, " ");
   strcat(s,yyvsp[-1].str);strcat(s, " ");
   strcat(s,yyvsp[0].str);strcat(s, "\n");
   yyval.str=s;
;
    break;}
case 58:
#line 511 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-10].str)+strlen(yyvsp[-9].str)+strlen(yyvsp[-8].str)+strlen(yyvsp[-7].str)+strlen(yyvsp[-6].str)+strlen(yyvsp[-5].str)+strlen(yyvsp[-4].str)+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+16));
   strcpy(s, yyvsp[-10].str);strcat(s, " ");
   strcat(s,yyvsp[-9].str);strcat(s, " ");
   strcat(s,yyvsp[-8].str);strcat(s, " ");
   strcat(s,yyvsp[-7].str);strcat(s, " ");
   strcat(s,yyvsp[-6].str);strcat(s, " ");
   strcat(s,yyvsp[-5].str);strcat(s, " ");
   strcat(s,yyvsp[-4].str);strcat(s, "\n");
   strcat(s,yyvsp[-3].str);strcat(s, " ");
   strcat(s,yyvsp[-2].str);strcat(s, " ");
   strcat(s,yyvsp[-1].str);strcat(s, " ");
   strcat(s,yyvsp[0].str);strcat(s, "\n");
   yyval.str=s;
;
    break;}
case 59:
#line 526 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-11].str)+strlen(yyvsp[-10].str)+strlen(yyvsp[-9].str)+strlen(yyvsp[-8].str)+strlen(yyvsp[-7].str)+strlen(yyvsp[-6].str)+strlen(yyvsp[-5].str)+strlen(yyvsp[-4].str)+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+16));
   strcpy(s, yyvsp[-11].str);strcat(s, " ");
   strcat(s,yyvsp[-10].str);strcat(s, " ");
   strcat(s,yyvsp[-9].str);strcat(s, " ");
   strcat(s,yyvsp[-8].str);strcat(s, " ");
   strcat(s,yyvsp[-7].str);strcat(s, " ");
   strcat(s,yyvsp[-6].str);strcat(s, "\n");
   strcat(s,yyvsp[-5].str);strcat(s, " ");
   strcat(s,yyvsp[-4].str);strcat(s, " ");
   strcat(s,yyvsp[-3].str);strcat(s, " ");
   strcat(s,yyvsp[-2].str);strcat(s, " ");
   strcat(s,yyvsp[-1].str);strcat(s, " ");
   strcat(s,yyvsp[0].str);strcat(s, "\n");
   yyval.str=s;
;
    break;}
case 60:
#line 542 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-10].str)+strlen(yyvsp[-9].str)+strlen(yyvsp[-8].str)+strlen(yyvsp[-7].str)+strlen(yyvsp[-6].str)+strlen(yyvsp[-5].str)+strlen(yyvsp[-4].str)+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+16));
   strcpy(s, yyvsp[-10].str);strcat(s, " ");
   strcat(s,yyvsp[-9].str);strcat(s, " ");
   strcat(s,yyvsp[-8].str);strcat(s, " ");
   strcat(s,yyvsp[-7].str);strcat(s, " ");
   strcat(s,yyvsp[-6].str);strcat(s, " ");
   strcat(s,yyvsp[-5].str);strcat(s, " ");
   strcat(s,yyvsp[-4].str);strcat(s, "\n");
   strcat(s,yyvsp[-3].str);strcat(s, " ");
   strcat(s,yyvsp[-2].str);strcat(s, " ");
   strcat(s,yyvsp[-1].str);strcat(s, " ");
   strcat(s,yyvsp[0].str);strcat(s, "\n");
   yyval.str=s;
;
    break;}
case 61:
#line 557 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-11].str)+strlen(yyvsp[-10].str)+strlen(yyvsp[-9].str)+strlen(yyvsp[-8].str)+strlen(yyvsp[-7].str)+strlen(yyvsp[-6].str)+strlen(yyvsp[-5].str)+strlen(yyvsp[-4].str)+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+16));
   strcpy(s, yyvsp[-11].str);strcat(s, " ");
   strcat(s,yyvsp[-10].str);strcat(s, " ");
   strcat(s,yyvsp[-9].str);strcat(s, " ");
   strcat(s,yyvsp[-8].str);strcat(s, " ");
   strcat(s,yyvsp[-7].str);strcat(s, " ");
   strcat(s,yyvsp[-6].str);strcat(s, " ");
   strcat(s,yyvsp[-5].str);strcat(s, "\n");
   strcat(s,yyvsp[-4].str);strcat(s, " ");
   strcat(s,yyvsp[-3].str);strcat(s, " ");
   strcat(s,yyvsp[-2].str);strcat(s, " ");
   strcat(s,yyvsp[-1].str);strcat(s, " ");
   strcat(s,yyvsp[0].str);strcat(s, "\n");
   yyval.str=s;
;
    break;}
case 62:
#line 573 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-11].str)+strlen(yyvsp[-10].str)+strlen(yyvsp[-9].str)+strlen(yyvsp[-8].str)+strlen(yyvsp[-7].str)+strlen(yyvsp[-6].str)+strlen(yyvsp[-5].str)+strlen(yyvsp[-4].str)+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+16));
   strcpy(s, yyvsp[-11].str);strcat(s, " ");
   strcat(s,yyvsp[-10].str);strcat(s, " ");
   strcat(s,yyvsp[-9].str);strcat(s, " ");
   strcat(s,yyvsp[-8].str);strcat(s, " ");
   strcat(s,yyvsp[-7].str);strcat(s, " ");
   strcat(s,yyvsp[-6].str);strcat(s, " ");
   strcat(s,yyvsp[-5].str);strcat(s, "\n");
   strcat(s,yyvsp[-4].str);strcat(s, " ");
   strcat(s,yyvsp[-3].str);strcat(s, " ");
   strcat(s,yyvsp[-2].str);strcat(s, " ");
   strcat(s,yyvsp[-1].str);strcat(s, " ");
   strcat(s,yyvsp[0].str);strcat(s, "\n");
   yyval.str=s;
;
    break;}
case 63:
#line 589 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-12].str)+strlen(yyvsp[-11].str)+strlen(yyvsp[-10].str)+strlen(yyvsp[-9].str)+strlen(yyvsp[-8].str)+strlen(yyvsp[-7].str)+strlen(yyvsp[-6].str)+strlen(yyvsp[-5].str)+strlen(yyvsp[-4].str)+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+16));
   strcpy(s, yyvsp[-12].str);strcat(s, " ");
   strcat(s,yyvsp[-11].str);strcat(s, " ");
   strcat(s,yyvsp[-10].str);strcat(s, " ");
   strcat(s,yyvsp[-9].str);strcat(s, " ");
   strcat(s,yyvsp[-8].str);strcat(s, " ");
   strcat(s,yyvsp[-7].str);strcat(s, " ");
   strcat(s,yyvsp[-6].str);strcat(s, "\n");
   strcat(s,yyvsp[-5].str);strcat(s, " ");
   strcat(s,yyvsp[-4].str);strcat(s, " ");
   strcat(s,yyvsp[-3].str);strcat(s, " ");
   strcat(s,yyvsp[-2].str);strcat(s, " ");
   strcat(s,yyvsp[-1].str);strcat(s, " ");
   strcat(s,yyvsp[0].str);strcat(s, "\n");
   yyval.str=s;
;
    break;}
case 64:
#line 608 "P1.y"
{
   yyval.str = yyvsp[0].str;
;
    break;}
case 65:
#line 611 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+2));
   strcpy(s, yyvsp[-1].str);strcat(s, "\n");
   strcat(s,yyvsp[0].str);strcat(s, " ");
   yyval.str=s;
;
    break;}
case 66:
#line 618 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-20].str)+strlen(yyvsp[-19].str)+strlen(yyvsp[-18].str)+strlen(yyvsp[-17].str)+strlen(yyvsp[-16].str)+strlen(yyvsp[-15].str)+strlen(yyvsp[-14].str)+strlen(yyvsp[-13].str)+strlen(yyvsp[-12].str)+strlen(yyvsp[-11].str)+strlen(yyvsp[-10].str)+strlen(yyvsp[-9].str)+strlen(yyvsp[-8].str)+strlen(yyvsp[-7].str)+strlen(yyvsp[-6].str)+strlen(yyvsp[-5].str)+strlen(yyvsp[-4].str)+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+25));
   strcpy(s, yyvsp[-20].str);strcat(s, " ");
   strcat(s,yyvsp[-19].str);strcat(s, " ");
   strcat(s,yyvsp[-18].str);strcat(s, "\n");
   strcat(s,yyvsp[-17].str);strcat(s, " ");
   strcat(s,yyvsp[-16].str);strcat(s, " ");
   strcat(s,yyvsp[-15].str);strcat(s, " ");
   strcat(s,yyvsp[-14].str);strcat(s, " ");
   strcat(s,yyvsp[-13].str);strcat(s, " ");
   strcat(s,yyvsp[-12].str);strcat(s, " ");
   strcat(s,yyvsp[-11].str);strcat(s, " ");
   strcat(s,yyvsp[-10].str);strcat(s, " ");
   strcat(s,yyvsp[-9].str);strcat(s, " ");
   strcat(s,yyvsp[-8].str);strcat(s, " ");
   strcat(s,yyvsp[-7].str);strcat(s, "\n");
   strcat(s,yyvsp[-6].str);strcat(s, " ");
   strcat(s,yyvsp[-5].str);strcat(s, " ");
   strcat(s,yyvsp[-4].str);strcat(s, " ");
   strcat(s,yyvsp[-3].str);strcat(s, " ");
   strcat(s,yyvsp[-2].str);strcat(s, "\n");
   strcat(s,yyvsp[-1].str);strcat(s, "\n");
   strcat(s,yyvsp[0].str);strcat(s, "\n");
   yyval.str=s;
;
    break;}
case 67:
#line 646 "P1.y"
{
      char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-4].str)+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+7));
      strcpy(s, yyvsp[-4].str);strcat(s, " ");
      strcat(s,yyvsp[-3].str);strcat(s, " ");strcat(s,yyvsp[-2].str);strcat(s, "\n");strcat(s, yyvsp[-1].str);strcat(s, " ");strcat(s, yyvsp[0].str);strcat(s, " ");
      yyval.str=s;
;
    break;}
case 68:
#line 652 "P1.y"
{
      char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-5].str)+strlen(yyvsp[-4].str)+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+7));
      strcpy(s, yyvsp[-5].str);strcat(s, " ");
      strcat(s,yyvsp[-4].str);strcat(s, " ");strcat(s,yyvsp[-3].str);strcat(s, "\n");strcat(s, yyvsp[-2].str);strcat(s, " ");strcat(s, yyvsp[-1].str);strcat(s, " ");strcat(s, yyvsp[0].str);strcat(s, " ");
      yyval.str=s;
;
    break;}
case 69:
#line 658 "P1.y"
{
      char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-4].str)+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+7));
      strcpy(s, yyvsp[-4].str);strcat(s, " ");
      strcat(s,yyvsp[-3].str);strcat(s, " ");strcat(s,yyvsp[-2].str);strcat(s, "\n");strcat(s, yyvsp[-1].str);strcat(s, " ");strcat(s, yyvsp[0].str);strcat(s, " ");
      yyval.str=s;
;
    break;}
case 70:
#line 664 "P1.y"
{
      char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+7));
      strcpy(s, yyvsp[-3].str);strcat(s, " ");
      strcat(s,yyvsp[-2].str);strcat(s, " ");strcat(s,yyvsp[-1].str);strcat(s, "\n");strcat(s, yyvsp[0].str);strcat(s, " ");
      yyval.str=s;
;
    break;}
case 71:
#line 670 "P1.y"
{
      char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-5].str)+strlen(yyvsp[-4].str)+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+8));
      strcpy(s, yyvsp[-5].str);strcat(s, " ");
      strcat(s,yyvsp[-4].str);strcat(s, " ");strcat(s,yyvsp[-3].str);strcat(s, " ");strcat(s, yyvsp[-2].str);strcat(s, " ");strcat(s, yyvsp[-1].str);strcat(s, "\n");strcat(s, yyvsp[0].str);strcat(s, " ");
      yyval.str=s;
;
    break;}
case 72:
#line 676 "P1.y"
{
      char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-6].str)+strlen(yyvsp[-5].str)+strlen(yyvsp[-4].str)+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+8));
      strcpy(s, yyvsp[-6].str);strcat(s, " ");
      strcat(s,yyvsp[-5].str);strcat(s, " ");strcat(s,yyvsp[-4].str);strcat(s, " ");strcat(s, yyvsp[-3].str);strcat(s, " ");strcat(s, yyvsp[-2].str);strcat(s, "\n");strcat(s, yyvsp[-1].str);strcat(s, " ");strcat(s, yyvsp[0].str);strcat(s, " ");
      yyval.str=s;
;
    break;}
case 73:
#line 682 "P1.y"
{
      char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-6].str)+strlen(yyvsp[-5].str)+strlen(yyvsp[-4].str)+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+8));
      strcpy(s, yyvsp[-6].str);strcat(s, " ");
      strcat(s,yyvsp[-5].str);strcat(s, " ");strcat(s,yyvsp[-4].str);strcat(s, " ");strcat(s, yyvsp[-3].str);strcat(s, " ");strcat(s, yyvsp[-2].str);strcat(s, "\n");strcat(s, yyvsp[-1].str);strcat(s, " ");strcat(s, yyvsp[0].str);strcat(s, " ");
      yyval.str=s;
;
    break;}
case 74:
#line 688 "P1.y"
{
      char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-7].str)+strlen(yyvsp[-6].str)+strlen(yyvsp[-5].str)+strlen(yyvsp[-4].str)+strlen(yyvsp[-3].str)+strlen(yyvsp[-2].str)+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+8));
      strcpy(s, yyvsp[-7].str);strcat(s, " ");
      strcat(s,yyvsp[-6].str);strcat(s, " ");strcat(s,yyvsp[-5].str);strcat(s, " ");strcat(s, yyvsp[-4].str);strcat(s, " ");strcat(s, yyvsp[-3].str);strcat(s, "\n");strcat(s, yyvsp[-2].str);strcat(s, " ");strcat(s, yyvsp[-1].str);strcat(s, " ");strcat(s, yyvsp[0].str);strcat(s, " ");
      yyval.str=s;
;
    break;}
case 75:
#line 696 "P1.y"
{yyval.str = yyvsp[0].str;;
    break;}
case 76:
#line 697 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+2));
   strcpy(s, yyvsp[-1].str);strcat(s, " ");
   strcat(s,yyvsp[0].str);strcat(s, " ");
   yyval.str=s;
;
    break;}
case 77:
#line 705 "P1.y"
{
   struct macro* check = head;
      while(check != NULL){
         if(strcmp(check->id, yyvsp[-5].str) == 0){
            flag = 1;
            break;
         }
         check = check->next;
      }
      struct macro* temp = (struct macro*)malloc(sizeof(struct macro));
      temp->id = malloc(sizeof(char)*(strlen(yyvsp[-5].str)+1));
      //temp->args = malloc(1000*sizeof(char*));
      temp->stmt = malloc(sizeof(char)*(strlen(yyvsp[-1].str)+1));
      strcpy(temp->stmt, yyvsp[-1].str);
      strcpy(temp->id, yyvsp[-5].str);
      int ind = 0;
      //temp->num = (int*)malloc(ind * sizeof(int));
      temp->num = ind;
      if(head == NULL){
         head = temp;
         curr = temp;
      }
      else{
         curr->next = temp;
         curr = temp;
      }
      //printf("%s\n%s\n%d", temp->id, temp->stmt, temp->num);
      yyval.str = "";
;
    break;}
case 78:
#line 734 "P1.y"
{
   struct macro* check = head;
      while(check != NULL){
         if(strcmp(check->id, yyvsp[-6].str) == 0){
            flag = 1;
            break;
         }
         check = check->next;
      }
      struct macro* temp = (struct macro*)malloc(sizeof(struct macro));
      temp->id = malloc(sizeof(char)*(strlen(yyvsp[-6].str)+1));
      temp->args = malloc(1000*sizeof(char*));
      temp->stmt = malloc(sizeof(char)*(strlen(yyvsp[-1].str)+1));
      strcpy(temp->stmt, yyvsp[-1].str);
      // char *t1;
      // char* copy = strdup(temp->stmt);
      // t1 = strtok(temp->stmt, " ");
      // while(t1 != NULL)
      // {
      //    strcat(ans, t1);
      //    t1 = strtok(NULL, " ");
      // }
      // temp->stmt = copy;
      strcpy(temp->id, yyvsp[-6].str);
      char* s = yyvsp[-4].str;
      char *t;
      t = strtok(s, ", ");
      int ind=0;
      while(t != NULL)
      {
         temp->args[ind] = t;
         ind++;
         t = strtok(NULL, ", ");
      }
      //temp->num = (int*)malloc(ind * sizeof(int));
      temp->num = ind;
      if(head == NULL){
         head = temp;
         curr = temp;
      }
      else{
         curr->next = temp;
         curr = temp;
      }
      //printf("%s\n%s\n%d", curr->id, curr->stmt, curr->num);
      yyval.str = "";
;
    break;}
case 79:
#line 781 "P1.y"
{
      struct macro* check = head;
      while(check != NULL){
         if(strcmp(check->id, yyvsp[-4].str) == 0){
            flag = 1;
            break;
         }
         check = check->next;
      }
      struct macro* temp = (struct macro*)malloc(sizeof(struct macro));
      temp->id = malloc(sizeof(char)*(strlen(yyvsp[-4].str)+1));
      temp->args = malloc(1000*sizeof(char*));
      temp->stmt = malloc(sizeof(char)*(strlen(yyvsp[0].str)+1));
      strcpy(temp->stmt, "");
      strcpy(temp->id, yyvsp[-4].str);
      int ind=0;
      //temp->num = (int*)malloc(ind * sizeof(int));
      temp->num = ind;
      if(head == NULL){
         head = temp;
         curr = temp;
      }
      else{
         curr->next = temp;
         curr = temp;
      }
      //printf("%s\n%s\n%d", curr->id, curr->stmt, curr->num);
      yyval.str = "";
;
    break;}
case 80:
#line 810 "P1.y"
{
   struct macro* check = head;
      while(check != NULL){
         if(strcmp(check->id, yyvsp[-5].str) == 0){
            flag = 1;
            break;
         }
         check = check->next;
      }
      struct macro* temp = (struct macro*)malloc(sizeof(struct macro));
      temp->id = malloc(sizeof(char)*(strlen(yyvsp[-5].str)+1));
      temp->args = malloc(1000*sizeof(char*));
      temp->stmt = malloc(sizeof(char)*(strlen(yyvsp[-1].str)+1));
      strcpy(temp->stmt, yyvsp[-1].str);
      strcpy(temp->id, yyvsp[-5].str);
      int ind=0;
      //temp->num = (int*)malloc(ind * sizeof(int));
      temp->num = ind;
      if(head == NULL){
         head = temp;
         curr = temp;
      }
      else{
         curr->next = temp;
         curr = temp;
      }
      //printf("%s\n%s\n%d", curr->id, curr->stmt, curr->num);
      yyval.str = "";
;
    break;}
case 81:
#line 839 "P1.y"
{
   struct macro* check = head;
      while(check != NULL){
         if(strcmp(check->id, yyvsp[-5].str) == 0){
            flag = 1;
            break;
         }
         check = check->next;
      }
      struct macro* temp = (struct macro*)malloc(sizeof(struct macro));
      temp->id = malloc(sizeof(char)*(strlen(yyvsp[-5].str)+1));
      temp->args = malloc(1000*sizeof(char*));
      temp->stmt = malloc(sizeof(char)*(strlen(yyvsp[0].str)+1));
      strcpy(temp->stmt, "");
      strcpy(temp->id, yyvsp[-5].str);
      char* s = yyvsp[-3].str;
      char *t;
      t = strtok(s, ", ");
      int ind=0;
      while(t != NULL)
      {
         temp->args[ind] = t;
         ind++;
         t = strtok(NULL, ", ");
      }
      //temp->num = (int*)malloc(ind * sizeof(int));
      temp->num = ind;
      if(head == NULL){
         head = temp;
         curr = temp;
      }
      else{
         curr->next = temp;
         curr = temp;
      }
      //printf("%s\n%s\n%d", curr->id, curr->stmt, curr->num);
      yyval.str = "";
;
    break;}
case 82:
#line 877 "P1.y"
{
   struct macro* check = head;
      while(check != NULL){
         if(strcmp(check->id, yyvsp[-6].str) == 0){
            flag = 1;
            break;
         }
         check = check->next;
      }
      struct macro* temp = (struct macro*)malloc(sizeof(struct macro));
      temp->id = malloc(sizeof(char)*(strlen(yyvsp[-6].str)+1));
      temp->args = malloc(1000*sizeof(char*));
      temp->stmt = malloc(sizeof(char)*(strlen(yyvsp[-1].str)+1));
      strcpy(temp->stmt, yyvsp[-1].str);
      strcpy(temp->id, yyvsp[-6].str);
      char* s = yyvsp[-4].str;
      char *t;
      t = strtok(s, ", ");
      int ind=0;
      while(t != NULL)
      {
         temp->args[ind] = t;
         ind++;
         t = strtok(NULL, ", ");
      }
      //temp->num = (int*)malloc(ind * sizeof(int));
      temp->num = ind;
      if(head == NULL){
         head = temp;
         curr = temp;
      }
      else{
         curr->next = temp;
         curr = temp;
      }
      //printf("%s\n%s\n%d", curr->id, curr->stmt, curr->num);
      yyval.str = "";
;
    break;}
case 83:
#line 918 "P1.y"
{yyval.str = yyvsp[0].str;;
    break;}
case 84:
#line 919 "P1.y"
{
   char* s = malloc(sizeof(char)*(1+7+strlen(yyvsp[-1].str)+strlen(yyvsp[0].str)+2));
   strcpy(s, yyvsp[-1].str);strcat(s, "\n");
   strcat(s,yyvsp[0].str);strcat(s, " ");
   yyval.str=s;
;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 927 "P1.y"

int main(int argc, char **argv)
{
yyparse();
return 0;
}
void yyerror(char* s)
{
printf("// Failed to parse macrojava code.");
}
